// THIS FILE IS AUTO-GENERATED BY scripts/generate-archive.js
// DO NOT EDIT MANUALLY. To update, add images to public/archive/ folders and run:
// node scripts/generate-archive.js

export interface ArchivePoster {
    id: string;
    title: string;
    time?: string;
    image: string;
}

export type EventSlug = 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'closing-rituals' | 'collaboration-events';

export const archivePosters: Record<EventSlug, ArchivePoster[]> = {
    "wednesday": [
        {
            "id": "wednesday-0",
            "title": " 6 _8pm",
            "time": "8PM",
            "image": "/archive/wednesday/ 6 _8pm.png"
        },
        {
            "id": "wednesday-5",
            "title": "5",
            "time": "",
            "image": "/archive/wednesday/5.png"
        },
        {
            "id": "wednesday-4",
            "title": "4",
            "time": "",
            "image": "/archive/wednesday/4.png"
        },
        {
            "id": "wednesday-3",
            "title": "3",
            "time": "",
            "image": "/archive/wednesday/3.png"
        },
        {
            "id": "wednesday-2",
            "title": "2",
            "time": "",
            "image": "/archive/wednesday/2.png"
        },
        {
            "id": "wednesday-1",
            "title": "1",
            "time": "",
            "image": "/archive/wednesday/1.png"
        }
    ],
    "thursday": [
        {
            "id": "thursday-12",
            "title": "20_9.30pm",
            "time": "9.30PM",
            "image": "/archive/thursday/20_9.30pm.png"
        },
        {
            "id": "thursday-10",
            "title": "19_9.30pm",
            "time": "9.30PM",
            "image": "/archive/thursday/19_9.30pm.png"
        },
        {
            "id": "thursday-9",
            "title": "18",
            "time": "",
            "image": "/archive/thursday/18.png"
        },
        {
            "id": "thursday-8",
            "title": "17",
            "time": "",
            "image": "/archive/thursday/17.png"
        },
        {
            "id": "thursday-7",
            "title": "16",
            "time": "",
            "image": "/archive/thursday/16.png"
        },
        {
            "id": "thursday-6",
            "title": "15",
            "time": "",
            "image": "/archive/thursday/15.png"
        },
        {
            "id": "thursday-5",
            "title": "14",
            "time": "",
            "image": "/archive/thursday/14.png"
        },
        {
            "id": "thursday-4",
            "title": "13",
            "time": "",
            "image": "/archive/thursday/13.png"
        },
        {
            "id": "thursday-3",
            "title": "12",
            "time": "",
            "image": "/archive/thursday/12.png"
        },
        {
            "id": "thursday-2",
            "title": "11",
            "time": "",
            "image": "/archive/thursday/11.png"
        },
        {
            "id": "thursday-1",
            "title": "10",
            "time": "",
            "image": "/archive/thursday/10.png"
        },
        {
            "id": "thursday-19",
            "title": "9",
            "time": "",
            "image": "/archive/thursday/9.png"
        },
        {
            "id": "thursday-18",
            "title": "8",
            "time": "",
            "image": "/archive/thursday/8.png"
        },
        {
            "id": "thursday-17",
            "title": "7",
            "time": "",
            "image": "/archive/thursday/7.png"
        },
        {
            "id": "thursday-16",
            "title": "6",
            "time": "",
            "image": "/archive/thursday/6.png"
        },
        {
            "id": "thursday-15",
            "title": "5",
            "time": "",
            "image": "/archive/thursday/5.png"
        },
        {
            "id": "thursday-14",
            "title": "4",
            "time": "",
            "image": "/archive/thursday/4.png"
        },
        {
            "id": "thursday-13",
            "title": "3",
            "time": "",
            "image": "/archive/thursday/3.png"
        },
        {
            "id": "thursday-11",
            "title": "2",
            "time": "",
            "image": "/archive/thursday/2.png"
        },
        {
            "id": "thursday-0",
            "title": "1",
            "time": "",
            "image": "/archive/thursday/1.png"
        }
    ],
    "friday": [
        {
            "id": "friday-24",
            "title": "31_9pm",
            "time": "9PM",
            "image": "/archive/friday/31_9pm.png"
        },
        {
            "id": "friday-23",
            "title": "30_9pm",
            "time": "9PM",
            "image": "/archive/friday/30_9pm.png"
        },
        {
            "id": "friday-21",
            "title": "29",
            "time": "",
            "image": "/archive/friday/29.png"
        },
        {
            "id": "friday-20",
            "title": "28",
            "time": "",
            "image": "/archive/friday/28.png"
        },
        {
            "id": "friday-19",
            "title": "27",
            "time": "",
            "image": "/archive/friday/27.png"
        },
        {
            "id": "friday-18",
            "title": "26",
            "time": "",
            "image": "/archive/friday/26.png"
        },
        {
            "id": "friday-17",
            "title": "25",
            "time": "",
            "image": "/archive/friday/25.png"
        },
        {
            "id": "friday-16",
            "title": "24",
            "time": "",
            "image": "/archive/friday/24.png"
        },
        {
            "id": "friday-15",
            "title": "23",
            "time": "",
            "image": "/archive/friday/23.png"
        },
        {
            "id": "friday-14",
            "title": "22",
            "time": "",
            "image": "/archive/friday/22.png"
        },
        {
            "id": "friday-13",
            "title": "21",
            "time": "",
            "image": "/archive/friday/21.png"
        },
        {
            "id": "friday-12",
            "title": "20",
            "time": "",
            "image": "/archive/friday/20.png"
        },
        {
            "id": "friday-10",
            "title": "19",
            "time": "",
            "image": "/archive/friday/19.png"
        },
        {
            "id": "friday-9",
            "title": "18",
            "time": "",
            "image": "/archive/friday/18.png"
        },
        {
            "id": "friday-8",
            "title": "17",
            "time": "",
            "image": "/archive/friday/17.png"
        },
        {
            "id": "friday-7",
            "title": "16",
            "time": "",
            "image": "/archive/friday/16.png"
        },
        {
            "id": "friday-6",
            "title": "15",
            "time": "",
            "image": "/archive/friday/15.png"
        },
        {
            "id": "friday-5",
            "title": "14",
            "time": "",
            "image": "/archive/friday/14.png"
        },
        {
            "id": "friday-4",
            "title": "13",
            "time": "",
            "image": "/archive/friday/13.png"
        },
        {
            "id": "friday-3",
            "title": "12",
            "time": "",
            "image": "/archive/friday/12.png"
        },
        {
            "id": "friday-2",
            "title": "11",
            "time": "",
            "image": "/archive/friday/11.png"
        },
        {
            "id": "friday-1",
            "title": "10",
            "time": "",
            "image": "/archive/friday/10.png"
        },
        {
            "id": "friday-30",
            "title": "9",
            "time": "",
            "image": "/archive/friday/9.png"
        },
        {
            "id": "friday-29",
            "title": "8",
            "time": "",
            "image": "/archive/friday/8.png"
        },
        {
            "id": "friday-28",
            "title": "7",
            "time": "",
            "image": "/archive/friday/7.png"
        },
        {
            "id": "friday-27",
            "title": "6",
            "time": "",
            "image": "/archive/friday/6.png"
        },
        {
            "id": "friday-26",
            "title": "5",
            "time": "",
            "image": "/archive/friday/5.png"
        },
        {
            "id": "friday-25",
            "title": "4",
            "time": "",
            "image": "/archive/friday/4.png"
        },
        {
            "id": "friday-22",
            "title": "3",
            "time": "",
            "image": "/archive/friday/3.png"
        },
        {
            "id": "friday-11",
            "title": "2",
            "time": "",
            "image": "/archive/friday/2.png"
        },
        {
            "id": "friday-0",
            "title": "1",
            "time": "",
            "image": "/archive/friday/1.png"
        }
    ],
    "saturday": [
        {
            "id": "saturday-25",
            "title": "32_9pm",
            "time": "9PM",
            "image": "/archive/saturday/32_9pm.png"
        },
        {
            "id": "saturday-24",
            "title": "31_9.30pm",
            "time": "9.30PM",
            "image": "/archive/saturday/31_9.30pm.png"
        },
        {
            "id": "saturday-23",
            "title": "30",
            "time": "",
            "image": "/archive/saturday/30.png"
        },
        {
            "id": "saturday-21",
            "title": "29",
            "time": "",
            "image": "/archive/saturday/29.png"
        },
        {
            "id": "saturday-20",
            "title": "28",
            "time": "",
            "image": "/archive/saturday/28.png"
        },
        {
            "id": "saturday-19",
            "title": "27",
            "time": "",
            "image": "/archive/saturday/27.png"
        },
        {
            "id": "saturday-18",
            "title": "26",
            "time": "",
            "image": "/archive/saturday/26.png"
        },
        {
            "id": "saturday-17",
            "title": "25",
            "time": "",
            "image": "/archive/saturday/25.png"
        },
        {
            "id": "saturday-16",
            "title": "24",
            "time": "",
            "image": "/archive/saturday/24.png"
        },
        {
            "id": "saturday-15",
            "title": "23",
            "time": "",
            "image": "/archive/saturday/23.png"
        },
        {
            "id": "saturday-14",
            "title": "22",
            "time": "",
            "image": "/archive/saturday/22.png"
        },
        {
            "id": "saturday-13",
            "title": "21",
            "time": "",
            "image": "/archive/saturday/21.png"
        },
        {
            "id": "saturday-12",
            "title": "20",
            "time": "",
            "image": "/archive/saturday/20.png"
        },
        {
            "id": "saturday-10",
            "title": "19",
            "time": "",
            "image": "/archive/saturday/19.png"
        },
        {
            "id": "saturday-9",
            "title": "18",
            "time": "",
            "image": "/archive/saturday/18.png"
        },
        {
            "id": "saturday-8",
            "title": "17",
            "time": "",
            "image": "/archive/saturday/17.png"
        },
        {
            "id": "saturday-7",
            "title": "16",
            "time": "",
            "image": "/archive/saturday/16.png"
        },
        {
            "id": "saturday-6",
            "title": "15",
            "time": "",
            "image": "/archive/saturday/15.png"
        },
        {
            "id": "saturday-5",
            "title": "14",
            "time": "",
            "image": "/archive/saturday/14.png"
        },
        {
            "id": "saturday-4",
            "title": "13",
            "time": "",
            "image": "/archive/saturday/13.png"
        },
        {
            "id": "saturday-3",
            "title": "12",
            "time": "",
            "image": "/archive/saturday/12.png"
        },
        {
            "id": "saturday-2",
            "title": "11",
            "time": "",
            "image": "/archive/saturday/11.png"
        },
        {
            "id": "saturday-1",
            "title": "10",
            "time": "",
            "image": "/archive/saturday/10.png"
        },
        {
            "id": "saturday-31",
            "title": "9",
            "time": "",
            "image": "/archive/saturday/9.png"
        },
        {
            "id": "saturday-30",
            "title": "8",
            "time": "",
            "image": "/archive/saturday/8.png"
        },
        {
            "id": "saturday-29",
            "title": "7",
            "time": "",
            "image": "/archive/saturday/7.png"
        },
        {
            "id": "saturday-28",
            "title": "6",
            "time": "",
            "image": "/archive/saturday/6.png"
        },
        {
            "id": "saturday-27",
            "title": "5",
            "time": "",
            "image": "/archive/saturday/5.png"
        },
        {
            "id": "saturday-26",
            "title": "4",
            "time": "",
            "image": "/archive/saturday/4.png"
        },
        {
            "id": "saturday-22",
            "title": "3",
            "time": "",
            "image": "/archive/saturday/3.png"
        },
        {
            "id": "saturday-11",
            "title": "2",
            "time": "",
            "image": "/archive/saturday/2.png"
        },
        {
            "id": "saturday-0",
            "title": "1",
            "time": "",
            "image": "/archive/saturday/1.png"
        }
    ],
    "closing-rituals": [
        {
            "id": "closing-rituals-2",
            "title": "3_6pm",
            "time": "6PM",
            "image": "/archive/closing-rituals/3_6pm.png"
        },
        {
            "id": "closing-rituals-1",
            "title": "2",
            "time": "",
            "image": "/archive/closing-rituals/2.png"
        },
        {
            "id": "closing-rituals-0",
            "title": "1",
            "time": "",
            "image": "/archive/closing-rituals/1.png"
        }
    ],
    "collaboration-events": [
        {
            "id": "collaboration-events-1",
            "title": "2_1pm to 10pm",
            "time": "1PM TO 10PM",
            "image": "/archive/collaboration-events/2_1pm to 10pm.jpg"
        },
        {
            "id": "collaboration-events-0",
            "title": "1",
            "time": "",
            "image": "/archive/collaboration-events/1.mp4"
        }
    ]
};
