const fs = require('fs');
const path = require('path');

const archiveDir = path.join(__dirname, '../public/archive');
const outputFile = path.join(__dirname, '../src/lib/posters-data.ts');

const events = ['wednesday', 'thursday', 'friday', 'saturday'];

const archiveData = {};

events.forEach(event => {
    const eventDir = path.join(archiveDir, event);

    // Ensure the event directory exists
    if (!fs.existsSync(eventDir)) {
        fs.mkdirSync(eventDir, { recursive: true });
    }

    // Read files in the directory
    const files = fs.readdirSync(eventDir);

    // Filter only images
    let posters = files.filter(file => {
        const ext = path.extname(file).toLowerCase();
        return ['.jpg', '.jpeg', '.png', '.webp', '.gif'].includes(ext);
    });

    // Map to objects with absolute path relative to public, and get file stats for sorting
    let posterObjects = posters.map((file, index) => {
        const titleWithoutExt = file.replace(/\.[^/.]+$/, "");
        // Extract leading number for sorting (if user names files "1.png", "2.png", etc.)
        const numTitle = parseInt(titleWithoutExt, 10);
        const sortVal = isNaN(numTitle) ? 0 : numTitle;

        return {
            id: `${event}-${index}`,
            title: titleWithoutExt,
            image: `/archive/${event}/${file}`,
            sortVal: sortVal
        };
    });

    // Sort descending by extracted number (newest/highest number first)
    posterObjects.sort((a, b) => b.sortVal - a.sortVal);

    // Remove sorting key as it's not needed in the final output
    archiveData[event] = posterObjects.map(({ id, title, image }) => ({ id, title, image }));
});

// Generate the TypeScript content
const tsContent = `// THIS FILE IS AUTO-GENERATED BY scripts/generate-archive.js
// DO NOT EDIT MANUALLY. To update, add images to public/archive/ folders and run:
// node scripts/generate-archive.js

export interface ArchivePoster {
    id: string;
    title: string;
    image: string;
}

export type EventSlug = 'wednesday' | 'thursday' | 'friday' | 'saturday';

export const archivePosters: Record<EventSlug, ArchivePoster[]> = ${JSON.stringify(archiveData, null, 4)};
`;

fs.writeFileSync(outputFile, tsContent, 'utf8');
console.log('Successfully generated src/lib/posters-data.ts from public/archive and sorted newest first!');
