const fs = require('fs');
const path = require('path');

const archiveDir = path.join(__dirname, '../public/archive');
const outputFile = path.join(__dirname, '../src/lib/posters-data.ts');

const events = ['wednesday', 'thursday', 'friday', 'saturday', 'closing-rituals', 'collaboration-events'];

const archiveData = {};

events.forEach(event => {
    const eventDir = path.join(archiveDir, event);

    // Ensure the event directory exists
    if (!fs.existsSync(eventDir)) {
        fs.mkdirSync(eventDir, { recursive: true });
    }

    // Read files in the directory
    const files = fs.readdirSync(eventDir);

    // Filter only images and videos
    let posters = files.filter(file => {
        const ext = path.extname(file).toLowerCase();
        return ['.jpg', '.jpeg', '.png', '.webp', '.gif', '.mp4', '.webm'].includes(ext);
    });

    // Map to objects with absolute path relative to public, and get file stats for sorting
    let posterObjects = posters.map((file, index) => {
        const titleWithoutExt = file.replace(/\.[^/.]+$/, "");

        // Match format: "30_9pm", "30_9 PM", etc -> extracts "30" and "9pm"
        const parts = titleWithoutExt.split('_');
        const numPart = parts[0].trim();

        // Time is optional. If not provided via "_", leave it empty or fallback
        const timePart = parts.length > 1 ? parts.slice(1).join(' ').trim().toUpperCase() : "";

        // Extract leading number for sorting
        const numTitle = parseInt(numPart, 10);
        const sortVal = isNaN(numTitle) ? 0 : numTitle;

        return {
            id: `${event}-${index}`,
            title: titleWithoutExt,
            time: timePart, // Add parsed time
            image: `/archive/${event}/${file}`,
            sortVal: sortVal
        };
    });

    // Sort descending by extracted number (newest/highest number first)
    posterObjects.sort((a, b) => b.sortVal - a.sortVal);

    // Remove sorting key as it's not needed in the final output
    archiveData[event] = posterObjects.map(({ id, title, time, image }) => ({ id, title, time, image }));
});

// Generate the TypeScript content
const tsContent = `// THIS FILE IS AUTO-GENERATED BY scripts/generate-archive.js
// DO NOT EDIT MANUALLY. To update, add images to public/archive/ folders and run:
// node scripts/generate-archive.js

export interface ArchivePoster {
    id: string;
    title: string;
    time?: string;
    image: string;
}

export type EventSlug = 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'closing-rituals' | 'collaboration-events';

export const archivePosters: Record<EventSlug, ArchivePoster[]> = ${JSON.stringify(archiveData, null, 4)};
`;

fs.writeFileSync(outputFile, tsContent, 'utf8');
console.log('Successfully generated src/lib/posters-data.ts from public/archive and sorted newest first!');
